apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: k8s-backend
  labels:
    app: backend
    tier: backend

data:
  # Server configuration
  PORT: "3000"

  # MongoDB configuration (Replica Set)
  MONGO_HOSTS: "mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017"
  MONGO_DB: "posts"
  MONGO_REPLICA_SET: "rs0"


