apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: k8s-backend  
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: abodiaa/backend-api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

          env:
            - name: MONGO_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_HOSTS 

            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_DB

            - name: MONGO_REPLICA_SET
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGO_REPLICA_SET
 
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT


          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
